version: '3'

networks:
  webnet:

volumes:
  mongodb-data:

services:
  mecab:
    build: mecab
    ports:
      - 3000:3000
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    command: yarn dev

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongo
